# Generated by Django 4.1.10 on 2023-08-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='Cidade',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Endereço',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='Sobrenome',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='CEP',
            field=models.CharField(default=34534567, max_length=8),
            preserve_default=False,
        ),
    ]
