# Generated by Django 4.1.10 on 2023-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_city_order_cidade_rename_email_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Endereço',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Cidade',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Nome',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Sobrenome',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='CEP',
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=123123123, max_length=20),
            preserve_default=False,
        ),
    ]
